name: Build-OpenWrt-EasyTier

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请填写发布Releases的版本号（留空不发布）'
        required: false
        default: ''
      text:
        description: '请填写发布的说明'
        required: false
        default: ''

# ✅ 并发控制：允许不同 tag 并行，不会互相取消
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.tag }}
  cancel-in-progress: true

env:
  TAG: "${{ github.event.inputs.tag }}"
  TZ: Asia/Shanghai

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - 23.05.5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache OpenWrt SDK
        uses: actions/cache@v4
        with:
          path: |
            /opt/openwrt-sdk-${{ matrix.arch }}-${{ matrix.sdk }}
            dl
          key: sdk-${{ matrix.arch }}-${{ matrix.sdk }}

      - name: Overwrite i18n file
        run: |
          cat > luci-app-easytier/root/etc/uci-defaults/luci-i18n-easytier-zh-cn << 'EOF'
          #!/bin/sh
          exit 0
          EOF

      - name: Building packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: easytier luci-app-easytier
          NO_REFRESH_CHECK: 1
          NO_SHFMT_CHECK: 1
          MAKEFLAGS: -j$(nproc)
          V: s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EasyTier-${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/

      - name: Create compress files
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "build_time=$(TZ=UTC-8 date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
          zip -j EasyTier-${{ env.TAG }}-${{ matrix.arch }}-${{ matrix.sdk }}.zip bin/packages/${{ matrix.arch }}/packages_ci/*

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            > ### ![](https://img.shields.io/badge/编译时间-${{ env.build_time }}-easytier?logo=github&labelColor=blue)![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ env.TAG }}/total?label=下载次数&logo=github)

            - **23.05.5** 内是 ipk 安装包，可以直接在 Kwrt 23.05.5 (x86_64) 上安装  
              `opkg install ./luci-app-easytier.ipk`

            ${{ github.event.inputs.text }}
          tag_name: ${{ env.TAG }}
          files: EasyTier-${{ env.TAG }}-${{ matrix.arch }}-${{ matrix.sdk }}.zip
